In [4]:
import numpy as np

**Dimensional array**

* Data in numpy is stored in array .
* Numpy is collection or grid of data.
* Data stored in numpy array should be of same datatype.

**1d array is calld vector.
2d array is called matrix.**

**1D Array**

Numpy store  collection of only one datatype 

In [5]:
a=np.array([1,2,3,4])

In [6]:
a

array([1, 2, 3, 4])

In [7]:
a=np.array([1,2,3.5]) # Here the integers are converted into float numbers implicitily  because numpy store only one datatype .
a

array([1. , 2. , 3.5])

In [8]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a=np.arange(10,20,2) # arange(first,last,step)
a

array([10, 12, 14, 16, 18])

numpy provides memory management.we can declare memory required to store data.

In [13]:
a=np.array([1,2,3,4],dtype=np.int8)   # Here we specified 8 bit width.so it can store data between -128 to 127.

In [14]:
a

array([1, 2, 3, 4], dtype=int8)

In [16]:
a=np.array([1,2,500,4],dtype=np.int8)  # Here 500 is out of range .so it can take any random number  within range you specified,

In [17]:
a   

array([  1,   2, -12,   4], dtype=int8)

**We can create  numpy array using linspace method**

In [18]:
a=np.linspace(10,20,5)   # linspace returns given no of  equispace number between range specified.Here 
                        # first  and last number are inclusive.
a                        #linspace(first,last(inclusive),count of nos)

array([10. , 12.5, 15. , 17.5, 20. ])

Attributes-shape and Dimension .They are used to fetch information.They are read only.

In [20]:
a.ndim

1

In [21]:
a.shape

(5,)

**2-D array**

In [22]:
a=np.array([[1,2,3],
            [4,5,6]])

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6]])

Attributes

In [24]:
a.ndim   # it gives infer about no of dimension.

2

In [25]:
a.shape  # it gives no of shape such as no of rows and columns.

(2, 3)

In [26]:
import numpy as np

**create a 2D array using methods.**

ones method return array containing 1's.

In [27]:
a=np.ones([3,4])    #ones(no of rows,no of columns)
a                   # zeros method takes no of rows and colums as input and return an aray containing Zeros


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
a=np.zeros([7,8])   # zeros method takes no of rows and colums as input and return an aray containing Zeros
a                   #zeros(no of rows,no of columns)
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

eye method

In [29]:
a=np.eye(3)    # it is also known as identity matrix.
a              # It returns an array contains 1's in diagonal position and all remaining zeros.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
a=np.eye(4,2)    #eye(no of rows,no of columns)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

diag method.It creates 2d array containing elements at the diagonal.It also used to fetch  daiagonal elements from an array.

In [33]:
d=np.diag([1,2,3,4])   # it creates 2d array containing elements at diagoanal.It always return square matrix.
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:
np.diag(d)         #diag  fetch  daiagonal elements from an  d array.

array([1, 2, 3, 4])

In [36]:
import numpy as np

In [39]:
a=np.array([[[1,2,3],
          [4,5,6],
           [7,8,9]],
          
          [[1,2,3],
          [4,5,6],
          [7,8,9]],
           
          [[1,2,3],
          [4,5,6],
           [7,8,9]]])

In [40]:
a    #3d  array it is collection of 2d arrays.

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

**List Vs numpy**

numpy is faster than list.
it contains homogeneous data.Memort alloc is optimised.
computation is faster as it built  on c in backend  as execution of c is faster compared to python.


In [41]:
import numpy as np
import time

In [55]:
intial_time=time.time()    #using list
a=0
for i in range(1000000):
    a=a+i
print(a)
final_time=time.time()
diff=final_time-intial_time
print(diff)

499999500000
0.14386534690856934


In [56]:
intial_time=time.time()    #using numpy
a=np.arange(1000000)
s=np.sum(a)
print(s)
final_time=time.time()
diff1=final_time-intial_time
print(diff1)

499999500000
0.005420207977294922


In [57]:
diff/diff1   # here numpy is 23 times faster than list

26.542403448579222

**Create random numpy array using rand() function **

In [58]:
a=np.random.rand(5)    # rand(no of numbers).It gives 5 positive random numbers.
a

array([0.3860198 , 0.32824554, 0.23125239, 0.60394227, 0.9216255 ])

**randn() It gives negative random numbers**

In [59]:
a=np.random.randn(5)    #library->module->method.
a

array([ 1.11924562, -1.79735548,  1.29743143,  0.23252213,  0.60265939])

**To know tthe datatype of numbers in array use dtype attribute**

In [60]:
a=np.array([1,2,3,4])
a.dtype

dtype('int64')

In [61]:
a=np.array([1,2,3,4],dtype=float)  # we can change datatype of numbers in numpy array using dtype attribute.
a

array([1., 2., 3., 4.])

**Complex array**

In [63]:
a=np.array([1+2j,5j])
print(a)
print(a.dtype)

[1.+2.j 0.+5.j]
complex128


In [65]:
a=np.array([[True,False],
          [False,False]])
print(a)
print(a.dtype)

[[ True False]
 [False False]]
bool


**Indexing in array**

In [66]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a[1]

1

In [68]:
a[-1]

9

In [69]:
a[0:5]

array([0, 1, 2, 3, 4])

In [71]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
a[2,2]

1.0

Assignment

In [73]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a[5]=220
a

array([  0,   1,   2,   3,   4, 220,   6,   7,   8,   9])

In [75]:
a[1:5]

array([1, 2, 3, 4])

In [2]:
def add(a,b):
    return a+5,b+5
add(9,4)

(14, 9)

In [6]:
import numpy as np 
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
 b=a[::2]   # here b is a view .It points to (same memory of a)oroginal array a.
             # but b does not create new memory 
 b

array([0, 2, 4, 6, 8])

In [10]:
b[1]=99 
b        # it gets reflected in a as b points a memory location.

array([ 0, 99,  4,  6,  8])

In [9]:
a

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

**To check two arrays point to same memory  we use shares_memory method**

In [11]:
np.shares_memory(a,b)  # it returns true when two arrays point to same memory location.

True

**To create new array such that changes do not reflected in original array  we use copy method**

In [12]:
b=a[::2].copy()  # it creates new array 
b

array([ 0, 99,  4,  6,  8])

In [13]:
b[4]=88   # change do not reflect in the original array 
b

array([ 0, 99,  4,  6, 88])

In [14]:
a

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

**Boolean Indexing: An array can also be indexed using boolean arrays**

In [16]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
a%2!=0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [21]:
mask=(a%2!=0)  # mask is boolean array  i.e it contains only false and True.our answer will be the value which has corresponding value True,


In [22]:
a[mask]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

**Integer Indexing: An array can also be indexed using integer arrays**

In [24]:
p=np.random.randint(30,50,10)
p

array([33, 43, 30, 41, 37, 32, 41, 41, 47, 44])

In [25]:
p[[0,1,3]]

array([33, 43, 41])

**Basic Operations in array**

In [26]:
a=np.array([1,2,3,4])

In [27]:
a+1   # it will be applied to every element in array

array([2, 3, 4, 5])

In [28]:
a-2

array([-1,  0,  1,  2])

In [29]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [30]:
a*2

array([2, 4, 6, 8])

In [40]:
a=np.array([1,2,3,4])

In [39]:
b=np.array([5,6,7,])

In [41]:
a+b    # it will be perform element wise adition operation.
       #But both arrays should be of same size.

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

**sin,cos,log,exp operations**

In [34]:
a

array([1, 2, 3, 4])

In [35]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [36]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [37]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [38]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**To perform operation in 2d array,array must be of same size corresponding element will be multiplied or subtracted or added or divided.**

In [44]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
b=np.diag([1,2,3,4])
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [48]:
a+b

array([[2., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 5.]])

**Dot Product**
a=[a1,a2,a3]
b=[b1,b2,b3]
DotProduct=a1b1+a2b2+a3b3

In [49]:
a=np.array([1,2,3])

In [50]:
b=np.array([5,6,7])

In [51]:
b.dot(a)

38

In [52]:
a.dot(b)

38

**To multiply two matrices of different size,we use dot method.**

In [56]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6],[8,9],[4,1]])

In [57]:
a.dot(b)

array([[33, 27],
       [84, 75]])

In [58]:
b.dot(a)

array([[29, 40, 51],
       [44, 61, 78],
       [ 8, 13, 18]])

**Array Comparison**

In [59]:
a=np.array([1,2,3,4])
b=np.array([1,3,3,4])

In [60]:
a==b   # it will do element wise comparison 

array([ True, False,  True,  True])

In [61]:
mask=(a==b)

In [62]:
a[mask]

array([1, 3, 4])

In [64]:
np.array_equal(a,b)  # it will do element wise compaarison if any one of th element is false it returns false,

False

In [65]:
a=np.array([1,0,1,1,])
b=np.array([1,1,1,1])

In [66]:
np.logical_and(a,b)

array([ True, False,  True,  True])

In [68]:
np.logical_or(a,b)

array([ True,  True,  True,  True])

**Computation on 1d array**

In [69]:
a=np.array([1,4,5,6])

In [70]:
np.sum(a)

16

In [71]:
np.max(a)

6

In [72]:
np.min(a)

1

In [73]:
np.argmin(a)    # it returns index of min number

0

In [74]:
np.argmax(a)    # it returns index of min number

3

In [75]:
np.mean(a)

4.0

In [76]:
np.median(a)

4.5

In [77]:
np.std(a)

1.8708286933869707

**Comptutation on 2d array**

**axis=1 ->column wise**

**axis=0 ->row wise**

In [79]:
a=np.array([[1,2,3],[4,5,6]])
np.sum(a,axis=0)    # it will perform operation row wise

array([5, 7, 9])

In [80]:
np.sum(a,axis=1)   # it perform column wise

array([ 6, 15])

In [86]:
a=np.array([[1,2,3],[4,5,6]])
a=np.sum(a,axis=0)
a

array([5, 7, 9])

In [90]:
c=np.sum(a)
print(a)
print(a.ndim)
print(c.dtype)
print(c.shape)

[5 7 9]
1
int64
()


**we can perform min max mean std median  on 2d arrays using axis concept.**

**Any, All methods.They accept boolean values**

**if any value in the passed array is true,any returns true.**

**if any value in the passed array is false,all returns false**



In [91]:
a=np.array([True,False,True])

In [92]:
np.all(a)

False

In [93]:
np.any(a)

True

In [97]:
a=np.array([1,2,3])
a<0

array([False, False, False])

In [95]:
np.all(a<0)

False

In [1]:
import numpy as np

In [3]:
x=np.array([1,2,3,4])
y=np.array([11,21,31,4])
z=np.array([51,2,23,94])
#x<y<Z

In [6]:
res1=(x<y)
res1

array([ True,  True,  True, False])

In [8]:
res2=(y<z)
res2

array([ True, False, False,  True])

In [10]:
res3=res1&res2

In [11]:
np.all(res3)   # X<y<z is false

False

**Flattening**  It is used to convert 2d array or more  into 1d array 

**ravel() is used to flatten array**

In [12]:
x=np.array([[1,2,3],
           [4,5,6]])   # 2d array converted into 1d array
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [14]:
x=np.array([[[1,2,3],
           [4,5,6]],       # 3d array is converted into 1d array
            [[4,6,7],
             [6,7,8]]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 4, 6, 7, 6, 7, 8])

**Transpose**

In [15]:
x=np.array([[1,2,3],
           [4,5,6]])

In [16]:
x.T   # it is used to return transpose of the matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

**Reshape**

Reshape is to be converted into such a manner that
total no of elements =order of the reshape matrix that you want.

In [17]:
x=np.array([[1,2,3],
           [4,5,6]])

In [19]:
np.reshape(x,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a=np.arange(18)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [22]:
np.reshape(a,(2,9))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [23]:
np.reshape(a,(2,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

**sort**

In [26]:
x=np.random.randint(1,20,10)
x

array([10, 19,  8, 18, 14, 18, 12,  3, 10,  2])

In [27]:
np.sort(x)

array([ 2,  3,  8, 10, 10, 12, 14, 18, 18, 19])

In [28]:
a[::-1]

array([17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,
        0])

**when sorting 2d array we need to mention whether to sort row wise or column wise**

In [30]:
a=np.random.randint(10,20,10).reshape(2,5)
a

array([[12, 17, 14, 19, 12],
       [10, 12, 16, 18, 15]])

In [31]:
np.sort(a,axis=0)   # it sorts elements row wise

array([[10, 12, 14, 18, 12],
       [12, 17, 16, 19, 15]])

In [32]:
np.sort(a,axis=1)   # it sorts elements column wise

array([[12, 12, 14, 17, 19],
       [10, 12, 15, 16, 18]])

**To mention the index of the sorted elements we use argsort() method.**

In [39]:
a=np.random.randint(1,20,10)
a


array([18, 16, 14, 12, 13,  7,  6, 16, 18,  9])

In [40]:
b=np.argsort(a)
b# it mention the index of the sorted elements.

array([6, 5, 9, 3, 4, 2, 1, 7, 0, 8])

In [45]:
a[b]  # indexing by integer and print sort elements.

array([ 6,  7,  9, 12, 13, 14, 16, 16, 18, 18])

In numpy,the mathemeatical operation are element wise,hence these arrays must have same size/shape.
But sometimes numpy can itself convert different shaped array of same shape using concept of broadcasting.

**Type1 Broadcasting- Rows are repeated**

**Type2 Broadcasting- Columns are repeated**

**Type3 Broadcasting- Rows and Columns are repeated**


In [53]:
x=np.arange(18).reshape(3,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [48]:
y=np.array([1,2,3,4,5,6])
y

array([1, 2, 3, 4, 5, 6])

In [49]:
x+y   #Type 1 broadcasting rows are repeated.

array([[ 1,  3,  5,  7,  9, 11],
       [ 7,  9, 11, 13, 15, 17],
       [13, 15, 17, 19, 21, 23]])

In [57]:
y=np.array([1,2,3]).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [58]:
x+y     # type 2 broadcasting columns are added.

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13],
       [15, 16, 17, 18, 19, 20]])

In [59]:
x=np.array([1,2,3])
y=np.array([[1],[2],[3]])

In [60]:
x+y   #type 3 broadcasting rows and columns are added.

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [61]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
x[0,1]

2

**converting 1d to 2d array**

**Tile function-constructs new array by repeating array.**

In [69]:
x=np.array([1,2,3])

In [70]:
np.tile(x,(2,1))    #tile(array,(no of times you want to repeat rows,no of times you want to repeat columns))

array([[1, 2, 3],
       [1, 2, 3]])

In [71]:
np.tile(x,(1,2)) 

array([[1, 2, 3, 1, 2, 3]])

In [72]:
np.tile(x,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [73]:
c=np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [74]:
np.tile(c,(2,1))

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [75]:
np.tile(c,(1,2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [76]:
np.tile(c,(2,2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

**convert 1d to 2d array**

In [77]:
x=np.array([1,2,3])

In [78]:
x[0:3]

array([1, 2, 3])

In [79]:
x[0:3,np.newaxis]    # it converts 1d to 2d array using new axis attribute,It creates new axis.

array([[1],
       [2],
       [3]])

In [80]:
x=np.array([[1,2,3],[4,5,6]])

In [81]:
x[0:2,0:2]   # slicing of 2d array x[no of rows,no of columns]

array([[1, 2],
       [4, 5]])